### PR TITLE
updating math delimiter

### PR DESCRIPTION
**Pull request by dcharrezt**

### CODE REVIEW

**Review by tfboyd — CHANGES_REQUESTED** [review]
Can you explain the need for the $$? The equation seems to render correctly as-is and the other equations are also single $, e.g. `$\\begin{equation}L_i`.

If it is broken I want to fix it, but I need a little more info to understand why the change is needed. Thank you for understanding.

**Comment by dcharrezt** [comment]
Hi @tfboyd,

It is rendered correctly as it is in the colab notebooks, but it is not in the website. If I am not wrong the website is generated from the notebooks.

Here is the link to the website where the formula is displayed as plain latex.

https://www.tensorflow.org/agents/tutorials/0_intro_rl#q-learning

Apologies for not being clear about the PR.

**Comment by tfboyd** [comment]
I knew I should have checked the website.  You are 100% correct.  Weird that only that one needs the double $$ and I am far from an expert on this syntax.  I'll do some more verification and thank you. I will get this merged as soon as I validate (ASAP). Thank you.

**Comment by tfboyd** [comment]
Second, third, or maybe forth try was a charm. This seems to get the job done in devsite (tensorflow.org), github, and colab.

`  "$\\begin{equation}Q^\\ast(s, a) = \\mathbb{E}[ r + \\gamma \\max_{a'} Q^\\ast(s', a') ]\\end{equation}$\n",`

I took a screen shot and made sure they match. Closing this PR because the {} did not fix the render issue.  On the plus side, without your PR I would not have tried everything and sadly only I can see the results of the devsite (tensorflow) conversion.  Thank you for inspiring getting this fixed.  I am 99% I figured it out.  But I need to get my internal change approved and then see it pass to devsite.  I did as much testing as I could and really hope this does it because this was not fun.  :-)

https://latex.wikia.org/wiki/List_of_LaTeX_symbols

**Comment by dcharrezt** [comment]
Great, happy that it helped at least a little bit!.

**Comment by tfboyd** [comment]
Verified:  https://www.tensorflow.org/agents/tutorials/0_intro_rl#q-learning

**Pull request closed without merging**
