### PR TITLE
Use a separate counter variable for train_step_counter in PPOAgent

### PR DESCRIPTION
**Pull request by leroidauphin**
Separate the train_step_counter in the PPOAgent into two parts: a new counter variable and the global step. This allows the agent.train_step_counter to be incremented exactly once per call to _train, while maintaining the existing behaviour that the global step counts the number of optimisation steps (incremented by num_epochs per call to _train).

### CODE REVIEW

**Comment by leroidauphin** [comment]
Proposed solution for #357

**Comment by tfboyd** [comment]
Looking for a reviewer.

**Comment by summer-yue** [comment]
Thanks for the contribution! I have a high level question. We are actually moving away from using `epoch_num` inside of ppo_agent.train, and handle epochs with tf.Data pipelines outside of the agent. Given that, is there still added benefit in separating train_step_counter and global step here?

**Comment by leroidauphin** [comment]
> Thanks for the contribution! I have a high level question. We are actually moving away from using `epoch_num` inside of ppo_agent.train, and handle epochs with tf.Data pipelines outside of the agent. Given that, is there still added benefit in separating train_step_counter and global step here?

Possibly not. The purpose of this PR was to make the `_train` method of the PPOAgent fulfil the requirement in the super class docstring that the `train_step_counter` is incremented exactly once. If moving to the `tf.Data` pipeline achieves that goal there is no need for this PR and it should be closed.
Is it possible to find out more about the plans to move to `tf.Data` pipelines?

**Comment by summer-yue** [comment]
Sounds good! Thank you. We have actually already marked the .gather_all() method in the replay buffers deprecated, and ask all new users to move to .as_dataset(). I could add some comments in the PPO agents' documentations too, and potentially get rid of epoch_num soon (how fast this can be done would depend on how many existing projects are relying on this).

Thanks again for the contribution. Closing this for now.

**Pull request closed without merging**
