### PR TITLE
Update dynamic_step_driver.py

### PR DESCRIPTION
**Pull request by ayansengupta17**
back_prop=False is deprecated. So updated it using tf.stop_gradient.

### CODE REVIEW

**Comment by ayansengupta17** [comment]
> @googlebot I signed it!

**Comment by tfboyd** [comment]
@ebrevdo   Can you take a quick look?  This has gotten really old, but all the tests passed and it would be nice to resolve or state why we need to let it go.

**Comment by ayansengupta17** [comment]
> @ebrevdo Can you take a quick look? This has gotten really old, but all the tests passed and it would be nice to resolve or state why we need to let it go.

I am also curious, any update would be nice! Thanks!

**Comment by wookayin** [comment]
@ayansengupta17 it'd be great if you can fix the code style properly following https://google.github.io/styleguide/pyguide.html.

**Comment by ebrevdo** [comment]
Lgtm modulo style.

**Comment by tfboyd** [comment]
@wookayin  There are 3 line changes. Are we talking there is a lint error like the line is too long or something bigger I am not seeing?  I have not gotten around to adding a lint check to presubmit and without that the author is a bit blind as to the issue.

@ayansengupta17   The line numbers might be a little off but here are the lint errors. I know it is super annoying that you cannot see them. I suggest making sure you use pylint and set the line length limit to 80.  I do not know if there is a link link to the correct pylint settings to use, but I wish I had a link to share. We are in the middle of performance reviews or I would just clone your pr and fix these lint issues myself to get it done. I think the data below will allow you to fix it. I might finally be tired enough of these lint errors to make a presubmit check we can all see or is atleast something we can quickly share.:

```
CheckLint/0: Warning (/py/tf_agents/METADATA:77:3)
CheckLint found errors.
Line too long (89/80) [line-too-long]
	/py/tf_agents/drivers/dynamic_step_driver.py:181
Exactly one space required after assignment
    [_, time_step, policy_state] =  tf.nest.map_structure(tf.stop_gradient,tf.while_loop(
                                 ^
[bad-whitespace]
	/tf_agents/drivers/dynamic_step_driver.py:181
Exactly one space required after comma
    [_, time_step, policy_state] =  tf.nest.map_structure(tf.stop_gradient,tf.while_loop(
                                                                          ^
[bad-whitespace]
	/tf_agents/drivers/dynamic_step_driver.py:181
```

**Review by yochliu8 — APPROVED** [review]

**Pull request merged**
