### PR TITLE
Fix Issue 776: Incorect example to run dqn_train_eval_rnn.py

### PR DESCRIPTION
**Pull request by karnehm**
Fixing error in description to execute example of `dqn_train_eval_rnn.py` as described in #776.

### CODE REVIEW

**Comment by tfboyd** [comment]
@karnehm   You have to "sign" the cla, the link is in the checks section. I forgot about this fix, sorry.  I did get 5 PRs submitted.  If you don't sign it I'll try to remember to copy in the fix manually.

**Comment by karnehm** [comment]
Now I hope this solved the issue with cla

**Comment by tfboyd** [comment]
PERFECT, I'll get the +2ed and stuff.  Thank you, a small but very nice change.  Really appreciate it. I spent a lot of 20% time trying to make sure OSS keeps working smoothly.  gym changing APIs on me is a pain. Internally we are move forward slower.

**Comment by tfboyd** [comment]
Well this didn't get merged.  I am making a final push to get some old PRs merged. This is on my list. It will either get in in the next 3-4 days or likely never.  Sorry for the absurd delay.  Not sure why it didn't make it back in SEPT, it looks like we did everything correctly.

**Pull request merged**
