### PR TITLE
Changed, if possible, http:// to https://

### PR DESCRIPTION
**Pull request by Denbergvanthijs**
Changed http:// to https:// if possible

Some URLs are skipped:

404 error on:
https://incompleteideas.net/book/the-book-2nd.html
https://rob.schapire.net/papers/www10.pdf

Invalid certificates:
https://proceedings.mlr.press/v28/agrawal13.pdf
https://proceedings.mlr.press/v28/agrawal13-supp.pdf

Dead link:
http://downloads.tor-lattimore.com/book.pdf

https://www.mujoco.org/ links to a somewhat different page than http://www.mujoco.org/

I've also noticed the LICENSE is missing the copyright year and name of the owner at line 191. But this is maybe something for a different PR.

Kind regards,
Thijs

### CODE REVIEW

**Comment by tfboyd** [comment]
This is going to be impossible to accept. It breaks the notebooks. I added myself as a reviewer. I will look at making a couple blanked changes like the Apache License (which we add with a script) and mujoco as well as see if I can make a few other improvements. This is a good thing to point out, it just cannot be done in a huge PR.  I will leave this PR open until I can take some action and update the comments with what changes have been made. I am sorry I cannot take the PR as is.

**Comment by Denbergvanthijs** [comment]
Thank you for your feedback! I was reading [Google's transparency report](https://transparencyreport.google.com/https/overview?hl=en) and noticed the goal of achieving 100% encryption across all products.

**Comment by tfboyd** [comment]
Alright, i have  CLs for: 

  * The copyright Apache license link r/http/https and r/2018/2020. and
  * https://www-anw.cs.umass.edu/~barto/courses/cs687/williams92simple.pdf
  * LICENSE file updated 
  * I have no idea what is up with mujoco.org but their https is a mess and even redirects not to the index so I don't want to change that.
  * CL for the bandits book link being broken in review.
  * That should do it, the rest dont' support https or are messed up in some way. 

Leaving this open until they are submitted.  I am looking at the mujoco links. and a few of the other deadlinks. Not sure what i can do about expiring certs but I will do a quick check to understand the situation before "giving up".  I will update this PR.  The best I could do is give this PR a shout out my PR/CL comments.  Sorry I could not accept the PR "as-is". I love getting credit and I hate when I cannot accept PRs so people have a fun history contributing.

**Comment by tfboyd** [comment]
Marking closed. The main CLs are in and the final two are in review. I am confident they will get processed today or tomorrow depending on the reviewers timezone.

**Pull request closed without merging**
