### PR TITLE
CounterV2 deprecated substituted with Dataset.Counter

### PR DESCRIPTION
**Pull request by tiamilani**
I noticed a warning from TensorFlow running a simple replay buffer. The warning refers to the fact that `tf.data.experimental.counter` is deprecated and should be substituted with `tf.data.Dataset.counter`.
TensorFlow version: 2.11

### CODE REVIEW

**Comment by tfboyd** [comment]
I know this is about 9 months later, this is still a valid CL, I fixed the minor conflict and I will see if I can get this pushed through in the next few days. 

I am doing a final cleanup of PRs before I move do a new project.  Sorry it was so long; but it is still fun to get a PR accepted and have it in the history.

**Comment by tiamilani** [comment]
> but it is still fun to get a PR accepted and have it in the history.

No worries, it's indeed still nice to have a PR accepted ;)
But I noticed that the review failed due to an internal CI error unfortunately :(

**Comment by tfboyd** [comment]
It will be fine. I am working it through the system.  I am making sure the
~5 PRs that are out there get in. I need to fix an internal CI thing, but I
have confirmed your PR is totally fine.

**Comment by tiamilani** [comment]
Perfect, thanks for the confirmation :)

**Pull request merged**
