### PR TITLE
port tf_agents.agents.dqn.examples.v2.train_eval_test.py to TF2.0

### PR DESCRIPTION
**Pull request by tagomatech**
File accompanying the proposed `tf_agents.agents.dqn.examples.v3.train_eval.py` file in #240

### CODE REVIEW

**Comment by ebrevdo** [comment]
I'm confused @tagomatech , but i thought the v2 version is supposed to work with TF2.  Did you have issues with DQN v2 train_eval_test in TF2?

**Comment by tagomatech** [comment]
> I'm confused @tagomatech , but i thought the v2 version is supposed to work with TF2. Did you have issues with DQN v2 train_eval_test in TF2?

hi @ebrevdo.
I'm sorry that I may have got you or anyone confused.
the v2 version is working well with TF2.
what I did is somewhat cleaning V2 with "pure" TF2 functions, for instances replacing `tf.compat.v1` and `tf.compat.v2` functions as detailed in pull request #240 .
hopefully i have the correct understanding of changes made to TF.
thank you.

**Comment by tfboyd** [comment]
I will pick this up.  The V3 folder will not work but if we can remove all the compat stuff and use your V3 as our V2 that would be great.  There is a bit of work to test and verify global step works ok this way; but I think the effort is worth it.  Sorry for the huge gap, if I cannot resolve this is in 30 days (I know still a long time) we will have to close as too stale.  I will do my best to get some conclusion.

**Comment by tfboyd** [comment]
We/I appreciate the work you did to make a cleaner V2 implementation.  We are about to redo the examples again with a common learner.  I appreciate the time that you took and I am sorry the outcome it to just close this.

**Pull request closed without merging**
