### PR TITLE
Account for episode boundary with non-zero discount in DQN n-step update

### PR DESCRIPTION
**Pull request by mhe500**
Addresses TODO(b/134618876)

I welcome any feedback on the fix.

### CODE REVIEW

**Comment by nealwu** [comment]
Thanks Michael! We have some replay buffer changes in mind that may result in changing the solution that's needed for this issue, but I'll try to take a look at this soon.

**Comment by ebrevdo** [comment]
Sorry for the delay.  @oars perhaps your PR will resolve this?

**Comment by tfboyd** [comment]
@oars @kbanoop   I put a comment on the internal bug and bumped it to a P1 for visibility until this PR is resolved (merged or closed).

**Comment by tfboyd** [comment]
Too much time has passed. We were able to save some of these olds ones back in Feb but this one never made it.

**Pull request closed without merging**
