### PR TITLE
Add test to verify behaviour

### PR DESCRIPTION
**Pull request by johnamcleod**

### CODE REVIEW

**Comment by egonina** [comment]
Thanks for the PR!

**Comment by egonina** [comment]
Hi @johnamcleod, I'm running your PR internally but am getting a test error, here's the trace: 

```
Traceback (most recent call last):
  File "/build/work/4545f2577309b37cfcb3b52e256d48a9bee4/google3/runfiles/google3/third_party/py/tf_agents/utils/tensor_normalizer_test.py", line 318, in testVarianceEstimate
    self.assertAllClose(tfp.stats.variance(tensor), var[0])
  File "/build/work/4545f2577309b37cfcb3b52e256d48a9bee4/google3/runfiles/google3/third_party/tensorflow/python/framework/test_util.py", line 1233, in decorated
    return f(*args, **kwds)
  File "/build/work/4545f2577309b37cfcb3b52e256d48a9bee4/google3/runfiles/google3/third_party/tensorflow/python/framework/test_util.py", line 2720, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/build/work/4545f2577309b37cfcb3b52e256d48a9bee4/google3/runfiles/google3/third_party/tensorflow/python/framework/test_util.py", line 2680, in _assertAllCloseRecursive
    (path_str, path_str, msg)))
  File "/build/work/4545f2577309b37cfcb3b52e256d48a9bee4/google3/runfiles/google3/third_party/tensorflow/python/framework/test_util.py", line 2615, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg="\n".join(msgs), equal_nan=True)
  File "/build/work/4545f2577309b37cfcb3b52e256d48a9bee4/google3/runfiles/google3/third_party/py/numpy/testing/_private/utils.py", line 1501, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/build/work/4545f2577309b37cfcb3b52e256d48a9bee4/google3/runfiles/google3/third_party/py/numpy/testing/_private/utils.py", line 827, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=1e-06
Mismatched value: a is different from b. 
not close lhs = 0.25
not close rhs = 2.5
not close dif = 2.25
not close tol = 3.4999999999999995e-06
dtype = float32, shape = ()
Mismatch: 100%
Max absolute difference: 2.25
Max relative difference: 0.9
 x: array(0.25, dtype=float32)
 y: array(2.5, dtype=float32)
```

Were you able to successfully run this test on your end?

**Comment by johnamcleod** [comment]
Hi @egonina . My apologies - this PR is connected to the linked issue, but I did not describe the purpose of the PR here.

I raised this PR in response to a request by @sguada on the linked issue to create a test which demonstrates what I believe to be an inconsistency in the `StreamingTensorNormalizer`. This test was intended to fail. I hope this has not been an inconvenience for you.

**Comment by tfboyd** [comment]
@johnamcleod I am 80% sure I am about to do some surgery on the normalizer which may or may not result in me being able to address the issues your test catches.  Maybe I can take a look.  There is an issue where it does not respect the tensorspec and assumes everything is float32 and mujoco externally (open source) is float64 which is yet another thing I think needs changed. I fix this stuff in my 20% time, which seems hilarious given the pandemic, so it is slow going.

**Comment by ebrevdo** [comment]
@tfboyd this looks like a much more serious issue than float32 vs. float64.  assigning @oars since ethan originally wrote this.  Oscar; I think this class has many issues and needs to be revamped to use [Chan's parallel algorithm](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Parallel_algorithm), an extension of Wellford's single-pass algorithm - where `n_a` is the total sample size and `n_b` is the batch size of the incoming data.

**Comment by oars** [comment]
Funnily enough I did Welford's algorithm last week for some other project. Meeting with @tfboyd today since he did some work on this and we'll follow up.

**Comment by tfboyd** [comment]
@sguada  Did some internal testing and it looks like we have many eyes on this for 1, 2, and maybe 3 reasons which is great. Just another update. We have a P1 (high priority) but on this internally and that usually drives these issues to a conclusion. I think a current issue is the fix breaks existing saved models so there is a bit of discussion to sort it out.

**Comment by oars** [comment]
Thanks for the PR. Chan's method is now being used and there are similar tests covering the correctness of the variance and mean.

Thank you for raising this issue and presenting a simple test to reproduce it. This was a serious bug you identified!

**Pull request closed without merging**
