### PR TITLE
Fix for #281 unused variable in DQN tutorial

### PR DESCRIPTION
**Pull request by Denbergvanthijs**
I have noticed `initial_collect_steps` wasn't used in the DQN tutorial. Issue #281 has also addressed this.

Kind regards,
Thijs

### CODE REVIEW

**Comment by Denbergvanthijs** [comment]
@googlebot I signed it!

**Comment by tfboyd** [comment]
Nice, it is so easy to miss this stuff and the story as to why gets lost.

**Comment by Denbergvanthijs** [comment]
Thank you for merging my first ever commit on a big public repo!

**Comment by tfboyd** [comment]
@Denbergvanthijs  I can tell you that I 100% understand your excitement. It is also a big reason we (tf-agents) try to merge the PRs. Also this is a nice catch if I had upgraded my testing script to say manipulate the number of steps thinking that variable was setting the value I would have been annoyed. 

Thank you for taking the time to build a PR and for reading the tutorial.

**Pull request merged**
