### PR TITLE
fix code style

### PR DESCRIPTION
**Pull request by pana1990**
camel case to snake case

### CODE REVIEW

**Comment by pana1990** [comment]
I signed it!

**Review by kbanoop — COMMENTED** [review]
Thanks for the contribution! I agree we usually follow snake_case for function names, but for some reason, we use CamelCase for function names in our tests through most of the codebase. So I would rather keep it as it is for consistency

**Comment by pana1990** [comment]
@kbanoop thanks for your reply, In my honest opinion we should follow a consistent standard for the code style like STYLE_GUIDE.md say "TF Agents Style Guide say "Follow the TensorFlow style guide"

sorry for my poor english in advanced :/

**Comment by kbanoop** [comment]
Agree, but TensorFlow also follows the same `CamelCase for test names` style. 

See e.g. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/kernel_tests/flat_map_test.py

**Pull request merged**
